package com.example.soulitem;

import org.bukkit.NamespacedKey;
import org.bukkit.plugin.java.JavaPlugin;

/**
 * SoulItem - REAL Custom Item Plugin (NOT a texture pack)
 * Generated by Custom Item Maker.
 *
 * This plugin registers a REAL custom item ("soul_blade") server-side via
 * PersistentDataContainer (NBT tag). The item's identity lives in its NBT data,
 * NOT in CustomModelData. CustomModelData is only used for the optional texture
 * pack that changes its appearance.
 *
 * Without this plugin: a diamond_sword (or whatever baseItem) is just a regular
 * vanilla item. With this plugin: the NBT tag makes it "soul_blade" with all
 * abilities, custom attributes, and crafting recipes.
 *
 * Target: Java 21 / Bukkit / Spigot / Paper (api-version 1.21.4).
 * Designed to be tolerant across MC versions using NamespacedKey lookups and
 * defensive reflection where APIs differ between versions.
 */
public class SoulItemPlugin extends JavaPlugin {

    private static SoulItemPlugin instance;
    private NamespacedKey itemKey;
    private CustomItemManager itemManager;
    private AbilityManager abilityManager;
    private RecipeManager recipeManager;

    @Override
    public void onEnable() {
        instance = this;
        saveDefaultConfig();

        this.itemKey = new NamespacedKey(this, "soul_blade");
        this.itemManager = new CustomItemManager(this);
        this.abilityManager = new AbilityManager(this);
        this.recipeManager = new RecipeManager(this);

        // Register listeners and recipes.
        getServer().getPluginManager().registerEvents(abilityManager, this);
        recipeManager.registerRecipes();

        // Register the give command.
        var cmd = getCommand("givesoulitem");
        if (cmd != null) {
            cmd.setExecutor(new GiveCommand(this));
        } else {
            getLogger().warning("Command 'givesoulitem' not found in plugin.yml");
        }

        getLogger().info("SoulItem v1.0.0 enabled. Item: soul_blade");
    }

    @Override
    public void onDisable() {
        if (recipeManager != null) recipeManager.unregisterRecipes();
        getLogger().info("SoulItem disabled.");
    }

    public static SoulItemPlugin getInstance() { return instance; }
    public NamespacedKey getItemKey() { return itemKey; }
    public CustomItemManager getItemManager() { return itemManager; }
    public AbilityManager getAbilityManager() { return abilityManager; }
    public RecipeManager getRecipeManager() { return recipeManager; }
}
